In [1]:
import warnings
warnings.filterwarnings('ignore')

import requests
from datetime import datetime
import pandas as pd
import time

si_url = 'https://new.land.naver.com/api/regions/list?cortarNo=0000000000'

r = requests.get(si_url, headers={
    "Accept-Encoding": "gzip, deflate, br",
    "Host": "new.land.naver.com",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "same-origin",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
})

data = r.json()
df_si = pd.DataFrame(data['regionList'])
df_si

      cortarNo  centerLat   centerLon cortarName cortarType
0   1100000000  37.566427  126.977872        서울시       city
1   4100000000  37.274939  127.008689        경기도       city
2   2800000000  37.456054  126.705151        인천시       city
3   2600000000  35.180143  129.075413        부산시       city
4   3000000000  36.350465  127.384953        대전시       city
5   2700000000  35.871390  128.601763        대구시       city
6   3100000000  35.538600  129.311375        울산시       city
7   3600000000  36.592907  127.292375        세종시       city
8   2900000000  35.160032  126.851338        광주시       city
9   4200000000  37.885399  127.729750        강원도       city
10  4300000000  36.636149  127.491238       충청북도       city
11  4400000000  36.636290  126.689570       충청남도       city
12  4700000000  36.518504  128.437796       경상북도       city
13  4800000000  35.238343  128.692400       경상남도       city
14  4500000000  35.820433  127.108875       전라북도       city
15  4600000000  34.816358  126.462443       전라남도       city
16  5000000000  33.488976  126.498238        제주도       city

In [52]:
tmp_si = '경기도'
cortar_no_si = df_si[df_si['cortarName'] == tmp_si].iloc[0,0]

gu_url = f'https://new.land.naver.com/api/regions/list?cortarNo={cortar_no_si}'

r = requests.get(gu_url, headers={
    "Accept-Encoding": "gzip, deflate, br",
    "Host": "new.land.naver.com",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "same-origin",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
})

data = r.json()
df_gu = pd.DataFrame(data['regionList'])
df_gu

      cortarNo  centerLat   centerLon cortarName cortarType
0   4182000000  37.831171  127.509625        가평군       dvsn
1   4128100000  37.637433  126.832359    고양시 덕양구       dvsn
2   4128500000  37.658790  126.775025   고양시 일산동구       dvsn
3   4128700000  37.675103  126.750578   고양시 일산서구       dvsn
4   4129000000  37.429201  126.987638        과천시       dvsn
5   4121000000  37.478587  126.864548        광명시       dvsn
6   4161000000  37.417461  127.255924        광주시       dvsn
7   4131000000  37.594409  127.129581        구리시       dvsn
8   4141000000  37.361610  126.935331        군포시       dvsn
9   4157000000  37.615267  126.715621        김포시       dvsn
10  4136000000  37.636032  127.216646       남양주시       dvsn
11  4125000000  37.903722  127.060579       동두천시       dvsn
12  4119000000  37.503548  126.766181        부천시       dvsn
13  4113500000  37.382820  127.118926    성남시 분당구       dvsn
14  4113100000  37.450396  127.145634    성남시 수정구       dvsn
15  4113300000  37.430523  127.137210    성남시 중원구       dvsn
16  4111300000  37.257607  126.971893    수원시 권선구       dvsn
17  4111700000  37.259116  127.046336    수원시 영통구       dvsn
18  4111100000  37.304160  127.010226    수원시 장안구       dvsn
19  4111500000  37.286537  127.035711    수원시 팔달구       dvsn
20  4139000000  37.380174  126.802938        시흥시       dvsn
21  4127300000  37.319537  126.811832    안산시 단원구       dvsn
22  4127100000  37.301140  126.845167    안산시 상록구       dvsn
23  4155000000  37.008018  127.279695        안성시       dvsn
24  4117300000  37.392574  126.951354    안양시 동안구       dvsn
25  4117100000  37.386649  126.932325    안양시 만안구       dvsn
26  4163000000  37.784952  127.045496        양주시       dvsn
27  4183000000  37.491776  127.487563        양평군       dvsn
28  4167000000  37.298342  127.637088        여주시       dvsn
29  4180000000  38.096872  127.075059        연천군       dvsn
30  4137000000  37.149889  127.077461        오산시       dvsn
31  4146300000  37.280156  127.114666    용인시 기흥구       dvsn
32  4146500000  37.322167  127.097962    용인시 수지구       dvsn
33  4146100000  37.234398  127.201597    용인시 처인구       dvsn
34  4143000000  37.344887  126.968279        의왕시       dvsn
35  4115000000  37.737933  127.033899       의정부시       dvsn
36  4150000000  37.278246  127.440997        이천시       dvsn
37  4148000000  37.759900  126.779760        파주시       dvsn
38  4122000000  36.992368  127.112763        평택시       dvsn
39  4165000000  37.894867  127.200240        포천시       dvsn
40  4145000000  37.539301  127.214874        하남시       dvsn
41  4159000000  37.199568  126.831325        화성시       dvsn

In [53]:
tmp_gu = '평택시'
cortar_no_gu = df_gu[df_gu['cortarName'] == tmp_gu].iloc[0,0]

dong_url = f'https://new.land.naver.com/api/regions/list?cortarNo={cortar_no_gu}'

r = requests.get(dong_url, headers={
    "Accept-Encoding": "gzip, deflate, br",
    "Host": "new.land.naver.com",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "same-origin",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
})

data = r.json()
df_dong = pd.DataFrame(data['regionList'])
df_dong

      cortarNo  centerLat   centerLon cortarName cortarType
0   4122010700  37.044000  127.084700        가재동        sec
1   4122012800  37.040530  127.050468        고덕동        sec
2   4122033000  37.042300  127.017745        고덕면        sec
3   4122011500  36.981300  127.088400        군문동        sec
4   4122010600  37.051058  127.110263        도일동        sec
5   4122011100  37.087000  127.069500        독곡동        sec
6   4122011900  37.015200  127.096500        동삭동        sec
7   4122010300  37.033400  127.077700        모곡동        sec
8   4122011800  37.002600  127.102200        비전동        sec
9   4122010100  37.066214  127.055765        서정동        sec
10  4122032000  37.108232  127.035325        서탄면        sec
11  4122012000  36.999915  127.082427        세교동        sec
12  4122012300  36.985101  127.127350        소사동        sec
13  4122012200  37.001575  127.065012        신대동        sec
14  4122011200  37.083700  127.051000        신장동        sec
15  4122025300  36.985810  126.931688        안중읍        sec
16  4122034000  37.007742  126.980313        오성면        sec
17  4122012400  37.000300  127.142100        용이동        sec
18  4122012500  37.022400  127.140000        월곡동        sec
19  4122011600  36.975500  127.111500        유천동        sec
20  4122010900  37.059400  127.068900        이충동        sec
21  4122010200  37.040400  127.063100        장당동        sec
22  4122010800  37.058742  127.084813        장안동        sec
23  4122012700  37.007500  127.125000        죽백동        sec
24  4122011000  37.077379  127.057577        지산동        sec
25  4122012100  37.018000  127.066900        지제동        sec
26  4122031000  37.099994  127.090536        진위면        sec
27  4122012600  37.025300  127.122700        청룡동        sec
28  4122025900  37.039900  126.934088        청북읍        sec
29  4122010400  37.032800  127.091400        칠괴동        sec
30  4122010500  37.025900  127.107700        칠원동        sec
31  4122011400  37.000815  127.087202        통복동        sec
32  4122025000  36.964887  127.062143        팽성읍        sec
33  4122011300  36.988562  127.084613        평택동        sec
34  4122025600  36.982943  126.885150        포승읍        sec
35  4122011700  36.985000  127.103600        합정동        sec
36  4122037000  36.967276  126.921500        현덕면        sec

In [54]:
tmp_dong = '비전동'
cortar_no_dong = df_dong[df_dong['cortarName'] == tmp_dong].iloc[0,0]
cortar_no_dong

'4122011800'

In [55]:
apt_list_url = f'https://new.land.naver.com/api/regions/complexes?cortarNo={cortar_no_dong}&realEstateType=APT%3AABYG&order='

r = requests.get(apt_list_url, headers={
    "Accept-Encoding": "gzip, deflate, br",
    "Host": "new.land.naver.com",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "same-origin",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
})

data = r.json()
df_apt_list = pd.DataFrame(data['complexList'])
sr_apt_no_list = df_apt_list['complexNo']

In [56]:
sr_apt_no_list

0      10441
1      27419
2     102196
3     141218
4      24419
5       2165
6       2859
7       2166
8       2167
9       2168
10     13949
11      2169
12     26915
13     10395
14      2170
15     27013
16     27305
17      2176
18     15185
19    107183
20     23036
21      2860
22     10300
23    138695
24      2175
25      9445
26     15188
27     10380
28     19066
29    108437
30     10292
31    152002
32     10320
33      2172
34      2173
35    137642
36     16258
37    103085
38    119641
39     19140
40     10355
41     11196
42     13168
43      2861
44      2858
45    115655
46      2177
Name: complexNo, dtype: object

In [57]:
import time

# df_list = []
df_all = None

for complex_no in sr_apt_no_list:
    for i in range(1,100):
        time.sleep(3)
        # location 직접 찍어서 범위 정하고 아파트 나오는 API 호출
        url = f'https://new.land.naver.com/api/articles/complex/{complex_no}?realEstateType=APT%3AABYG&tradeType=&tag=%3A%3A%3A%3A%3A%3A%3A%3A&rentPriceMin=0&rentPriceMax=900000000&priceMin=0&priceMax=900000000&areaMin=0&areaMax=900000000&oldBuildYears&recentlyBuildYears&minHouseHoldCount&maxHouseHoldCount&showArticle=false&sameAddressGroup=true&minMaintenanceCost&maxMaintenanceCost&priceType=RETAIL&directions=&page={i}&complexNo={complex_no}&buildingNos=&areaNos=&type=list&order=rank'

        # 개발자도구에서 request 정보도 입력해주어야 한다. 안그러면 로봇으로 인식해서 에러 발생한다.
        r = requests.get(url, headers={
            "Accept-Encoding": "gzip, deflate, br",
            "Host": "new.land.naver.com",
            "Referer": "https://new.land.naver.com/complexes/111552?ms=37.411486,126.6136355,17&a=APT:ABYG&e=RETAIL&ad=true",
            "Sec-Fetch-Dest": "empty",
            "Sec-Fetch-Mode": "cors",
            "Sec-Fetch-Site": "same-origin",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
            "authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlJFQUxFU1RBVEUiLCJpYXQiOjE2NjU1NzQ2MzEsImV4cCI6MTY2NTU4NTQzMX0.tWzkkkwSJRCzrFprNckpdRtamnDh0s3cSEhPBfuJgSE"
        })

        data = r.json()

        if len(data['articleList']) == 0:
            break
        # print(data)
        # print(len(data['articleList']))
        # print(len(data['articleList']))

        df_articleList = pd.DataFrame(data['articleList'])
        df_article = df_articleList[['articleName','realEstateTypeName','tradeTypeName','floorInfo','dealOrWarrantPrc','areaName','area2','buildingName','cpPcArticleUrl']].astype('str')
    #     df_list.append(df_article)
        df_all = pd.concat([df_all, df_article])
    print(df_all['articleName'].unique())
    time.sleep(3)

['SK비전']
['SK비전' 'YM프라젠']
['SK비전' 'YM프라젠' 'YM프라젠하우스']
['SK비전' 'YM프라젠' 'YM프라젠하우스']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차' '신명나리']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차' '신명나리' '신세계타운']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차' '신명나리' '신세계타운'
 '외기노조A지구']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차' '신명나리' '신세계타운'
 '외기노조A지구' '외기노조C지구']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차' '신명나리' '신세계타운'
 '외기노조A지구' '외기노조C지구' '우림필유']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차' '신명나리' '신세계타운'
 '외기노조A지구' '외기노조C지구' '우림필유' '우미린센트럴파크']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차' '신명나리' '신세계타운'
 '외기노조A지구' '외기노조C지구' '우림필유' '우미린센트럴파크' '은행']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차' '신명나리' '신세계타운'
 '외기노조A지구' '외기노조C지구' '우림필유' '우미린센트럴파크' '은행' '이곡마을6단지']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차' '신명나리' '신세계타운'
 '외기노조A지구' '외기노조C지구' '우림필유' '우미린센트럴파크' '은행' '이곡마을6단지' '진성']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차' '신명나리' '신세계타운'
 '외기노조A지구' '외기노조C지구' '우림필유' '우미린센트럴파크' '은행' '이곡마을6단지' '진성' '태산(태산그린)']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차' '신명나리' '신세계타운'
 '외기노조A지구' '외기노조C지구' '우림필유' '우미린센트럴파크' '은행' '이곡마을6단지' '진성' '태산(태산그린)'
 '태산신그린']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차' '신명나리' '신세계타운'
 '외기노조A지구' '외기노조C지구' '우림필유' '우미린센트럴파크' '은행' '이곡마을6단지' '진성' '태산(태산그린)'
 '태산신그린']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차' '신명나리' '신세계타운'
 '외기노조A지구' '외기노조C지구' '우림필유' '우미린센트럴파크' '은행' '이곡마을6단지' '진성' '태산(태산그린)'
 '태산신그린' '평택']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차' '신명나리' '신세계타운'
 '외기노조A지구' '외기노조C지구' '우림필유' '우미린센트럴파크' '은행' '이곡마을6단지' '진성' '태산(태산그린)'
 '태산신그린' '평택' '평택센트럴해링턴플레이스']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차' '신명나리' '신세계타운'
 '외기노조A지구' '외기노조C지구' '우림필유' '우미린센트럴파크' '은행' '이곡마을6단지' '진성' '태산(태산그린)'
 '태산신그린' '평택' '평택센트럴해링턴플레이스' '평택소사벌푸르지오']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차' '신명나리' '신세계타운'
 '외기노조A지구' '외기노조C지구' '우림필유' '우미린센트럴파크' '은행' '이곡마을6단지' '진성' '태산(태산그린)'
 '태산신그린' '평택' '평택센트럴해링턴플레이스' '평택소사벌푸르지오' '평택윤중수신제가']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차' '신명나리' '신세계타운'
 '외기노조A지구' '외기노조C지구' '우림필유' '우미린센트럴파크' '은행' '이곡마을6단지' '진성' '태산(태산그린)'
 '태산신그린' '평택' '평택센트럴해링턴플레이스' '평택소사벌푸르지오' '평택윤중수신제가' '평택진우']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차' '신명나리' '신세계타운'
 '외기노조A지구' '외기노조C지구' '우림필유' '우미린센트럴파크' '은행' '이곡마을6단지' '진성' '태산(태산그린)'
 '태산신그린' '평택' '평택센트럴해링턴플레이스' '평택소사벌푸르지오' '평택윤중수신제가' '평택진우']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차' '신명나리' '신세계타운'
 '외기노조A지구' '외기노조C지구' '우림필유' '우미린센트럴파크' '은행' '이곡마을6단지' '진성' '태산(태산그린)'
 '태산신그린' '평택' '평택센트럴해링턴플레이스' '평택소사벌푸르지오' '평택윤중수신제가' '평택진우' '한미']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차' '신명나리' '신세계타운'
 '외기노조A지구' '외기노조C지구' '우림필유' '우미린센트럴파크' '은행' '이곡마을6단지' '진성' '태산(태산그린)'
 '태산신그린' '평택' '평택센트럴해링턴플레이스' '평택소사벌푸르지오' '평택윤중수신제가' '평택진우' '한미' '한빛']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차' '신명나리' '신세계타운'
 '외기노조A지구' '외기노조C지구' '우림필유' '우미린센트럴파크' '은행' '이곡마을6단지' '진성' '태산(태산그린)'
 '태산신그린' '평택' '평택센트럴해링턴플레이스' '평택소사벌푸르지오' '평택윤중수신제가' '평택진우' '한미' '한빛' '한성']

['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차' '신명나리' '신세계타운'
 '외기노조A지구' '외기노조C지구' '우림필유' '우미린센트럴파크' '은행' '이곡마을6단지' '진성' '태산(태산그린)'
 '태산신그린' '평택' '평택센트럴해링턴플레이스' '평택소사벌푸르지오' '평택윤중수신제가' '평택진우' '한미' '한빛' '한성'
 '현대']
['SK비전' 'YM프라젠' 'YM프라젠하우스' '덕동마을신일유토빌' '동성한아름' '동성효성' '동아동백' '동아모란' '동아목련'
 '동아백합' '럭키덕동' '명진비전파크' '문화' '벽산' '비전경남아너스빌' '비전롯데캐슬' '비전현대' '새한'
 '소사벌리더스하임' '솔매마을한일유앤아이' '시대코아' '시대한우리' '신동아홈타운2차' '신명나리' '신세계타운'
 '외기노조A지구' '외기노조C지구' '우림필유' '우미린센트럴파크' '은행' '이곡마을6단지' '진성' '태산(태산그린)'
 '태산신그린' '평택' '평택센트럴해링턴플레이스' '평택소사벌푸르지오' '평택윤중수신제가' '평택진우' '한미' '한빛' '한성'
 '현대' '현대이화']

In [58]:
df_all.to_csv('./경기도_평택시_비전동_221013.csv', encoding='euc-kr', index=False)

In [66]:
df = pd.read_csv('./경기도_평택시_비전동_221013.csv', encoding='euc-kr')

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 698 entries, 0 to 697
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   articleName         698 non-null    object
 1   realEstateTypeName  698 non-null    object
 2   tradeTypeName       698 non-null    object
 3   floorInfo           698 non-null    object
 4   dealOrWarrantPrc    698 non-null    object
 5   areaName            698 non-null    object
 6   area2               698 non-null    int64
 7   buildingName        698 non-null    object
 8   cpPcArticleUrl      698 non-null    object
dtypes: int64(1), object(8)
memory usage: 49.2+ KB

In [60]:
# 데이터 불러오기
# df = pd.read_csv('./naver_article_all_region.csv', encoding='euc-kr')

# 억을 포함하는 가격 데이터 선정
df_over_billion = df[df['dealOrWarrantPrc'].str.contains('억')]

# 억을 기준으로 문자열을 쪼개고 억은 10000을 곱한다.
billion = df_over_billion['dealOrWarrantPrc'].str.split('억', expand=True)[0].astype('int') * 10000
thousand = df_over_billion['dealOrWarrantPrc'].str.split('억', expand=True)[1]

# 천 단위는 콤마를 포함하고 있기 때문에 제거한다.
thousand = thousand.map(lambda x: '0' if x == '' else x).str.replace(',', '').astype('int')

# 변환한 값을 가격 컬럼에 다시 넣는다.
df['dealOrWarrantPrc'] = billion + thousand

In [61]:
# 매매 데이터만 filter
df = df[df['tradeTypeName'] == '매매']

# 전용 84 평형 데이터만 filter
df_84 = df[(df['area2'] >= 80) & (df['area2'] < 90)]

# 최대, 최소의 index 구해서 filter
df_max = df_84.loc[df_84.groupby('articleName')['dealOrWarrantPrc'].idxmax(), :]
df_min = df_84.loc[df_84.groupby('articleName')['dealOrWarrantPrc'].idxmin(), :]

# 최대 최소 합쳐서 아파트별, 가격별 정렬하기
df_84_minmax = pd.concat([df_max, df_min]).sort_values(by=['articleName', 'dealOrWarrantPrc'], ascending=False)

In [62]:
sr_article_count_by_name = df_84.groupby('articleName').count()['dealOrWarrantPrc']
sr_article_count_by_name.name = 'article_count'
df_final = pd.merge(df_84_minmax, sr_article_count_by_name, left_on = 'articleName', right_index=True)

df_final = df_final[['articleName', 'realEstateTypeName', 'article_count', 'tradeTypeName', 'buildingName', 'floorInfo',
       'area2', 'areaName', 'dealOrWarrantPrc', 'cpPcArticleUrl']]
df_final.columns = ['아파트', '매물 종류', '매물 개수', '거래 종류', '동', '층', '전용 면적', '공급 타입', '가격', '매물 URL']
df_final

,아파트,매물 종류,매물 개수,거래 종류,동,층,전용 면적,공급 타입,가격,매물 URL
681,현대이화,아파트,4,매매,103동,4/13,84,101,30000.0,http://ten.co.kr/rd/rd.asp?UID=2234839008
689,현대이화,아파트,4,매매,104동,1/15,84,101,28000.0,http://land.mk.co.kr/rd/rd.php?UID=2232070377
629,평택소사벌푸르지오,아파트,31,매매,103동,저/23,83,112A,58000.0,http://www.serve.co.kr/naver/rd.asp?UID=223351...
589,평택소사벌푸르지오,아파트,31,매매,104동,1/24,83,112A,39000.0,http://ten.co.kr/rd/rd.asp?UID=2235755270
576,평택센트럴해링턴플레이스,아파트,62,매매,122동,저/15,84,111B,55000.0,http://www.karhanbang.com/naver_link.asp?UID=2...
514,평택센트럴해링턴플레이스,아파트,62,매매,120동,1/15,84,111A,37000.0,http://ten.co.kr/rd/rd.asp?UID=2235710462
459,우미린센트럴파크,아파트,32,매매,109동,중/25,84,110A,55000.0,http://land.mk.co.kr/rd/rd.php?UID=2233620118
429,우미린센트럴파크,아파트,32,매매,103동,12/24,84,109B,42000.0,http://ten.co.kr/rd/rd.asp?UID=2235712403
412,우림필유,아파트,11,매매,103동,11/15,84,109,30500.0,http://ten.co.kr/rd/rd.asp?UID=2233385813
414,우림필유,아파트,11,매매,103동,1/15,84,109,28000.0,http://ten.co.kr/rd/rd.asp?UID=2233753150
394,신세계타운,아파트,13,매매,102동,8/15,84,108,29500.0,http://www.serve.co.kr/naver/rd.asp?UID=223403...
393,신세계타운,아파트,13,매매,101동,저/15,84,108,24000.0,http://ten.co.kr/rd/rd.asp?UID=2235052776
340,솔매마을한일유앤아이,아파트,6,매매,101동,5/12,84,109,32000.0,http://www.serve.co.kr/naver/rd.asp?UID=223562...
344,솔매마을한일유앤아이,아파트,6,매매,103동,저/12,84,109,29000.0,http://www.serve.co.kr/naver/rd.asp?UID=223487...
287,소사벌리더스하임,아파트,53,매매,109동,20/24,84,111A,47000.0,http://land.mk.co.kr/rd/rd.php?UID=2234996943
266,소사벌리더스하임,아파트,53,매매,101동,1/22,84,111A,35000.0,http://ten.co.kr/rd/rd.asp?UID=2235709510
224,비전롯데캐슬,아파트,13,매매,103동,중/20,84,109A,45000.0,http://www.serve.co.kr/naver/rd.asp?UID=223398...
210,비전롯데캐슬,아파트,13,매매,108동,저/20,84,109B,36000.0,http://www.serve.co.kr/naver/rd.asp?UID=223573...
187,비전경남아너스빌,아파트,29,매매,106동,11/18,84,108A,41500.0,http://www.serve.co.kr/naver/rd.asp?UID=223260...
165,비전경남아너스빌,아파트,29,매매,105동,18/18,84,108B,36500.0,http://ten.co.kr/rd/rd.asp?UID=2234119933
143,벽산,아파트,5,매매,103동,11/18,84,105,30000.0,http://ten.co.kr/rd/rd.asp?UID=2234444324
145,벽산,아파트,5,매매,104동,17/17,84,105,26000.0,http://ten.co.kr/rd/rd.asp?UID=2231807424
85,럭키덕동,아파트,18,매매,106동,고/15,84,102,31000.0,http://www.serve.co.kr/naver/rd.asp?UID=223490...
92,럭키덕동,아파트,18,매매,105동,저/15,84,102,28000.0,http://land.kcrwork.com/partner/naver/redirect...
81,동아백합,아파트,2,매매,102동,14/16,84,107,27000.0,http://www.serve.co.kr/naver/rd.asp?UID=223545...
81,동아백합,아파트,2,매매,102동,14/16,84,107,27000.0,http://www.serve.co.kr/naver/rd.asp?UID=223545...
74,동아목련,아파트,15,매매,101동,중/20,84,102,30000.0,http://ten.co.kr/rd/rd.asp?UID=2232795745
63,동아목련,아파트,15,매매,101동,6/20,84,102,24000.0,http://www.serve.co.kr/naver/rd.asp?UID=223410...
53,동아모란,아파트,2,매매,102동,고/16,84,107,28500.0,http://www.serve.co.kr/naver/rd.asp?UID=223377...
51,동아모란,아파트,2,매매,102동,7/16,84,107,28000.0,http://www.serve.co.kr/naver/rd.asp?UID=223559...
46,동아동백,아파트,3,매매,103동,1/16,84,107,27500.0,http://www.serve.co.kr/naver/rd.asp?UID=223126...
45,동아동백,아파트,3,매매,103동,2/16,84,107,24000.0,http://land.kcrwork.com/partner/naver/redirect...
15,덕동마을신일유토빌,아파트,3,매매,1동,14/15,84,110B,30000.0,http://ten.co.kr/rd/rd.asp?UID=2233032394
14,덕동마을신일유토빌,아파트,3,매매,1동,1/15,84,110B,24500.0,http://ten.co.kr/rd/rd.asp?UID=2233845410
11,YM프라젠하우스,아파트,2,매매,102동,3/4,84,119B,35000.0,http://ten.co.kr/rd/rd.asp?UID=2235616973
12,YM프라젠하우스,아파트,2,매매,106동,1/4,84,119A,34000.0,http://land.mk.co.kr/rd/rd.php?UID=2231399372
5,SK비전,아파트,10,매매,102동,고/15,84,111,36000.0,http://ten.co.kr/rd/rd.asp?UID=2232210964
1,SK비전,아파트,10,매매,102동,2/15,84,111,30000.0,http://ten.co.kr/rd/rd.asp?UID=2233166095

In [162]:
import dataframe_image as dfi

dfi.export(df_final.reset_index(drop=True), './df_image.png', max_cols = -1, max_rows = -1, dpi=100)

objc[24304]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb5409bec8) and /Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/106.0.5249.103/Libraries/libGLESv2.dylib (0x116aa8668). One of the two will be used. Which one is undefined.
[1013/191359.942877:INFO:headless_shell.cc(660)] Written to file /var/folders/gh/cb238x210j78stqk8llz8_q40000gn/T/tmpg90sapgr/temp.png.
objc[24315]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb5409bec8) and /Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/106.0.5249.103/Libraries/libGLESv2.dylib (0x10e29f668). One of the two will be used. Which one is undefined.
[1013/191401.107714:INFO:headless_shell.cc(660)] Written to file /var/folders/gh/cb238x210j78stqk8llz8_q40000gn/T/tmpxkb3lvi7/temp.png.
objc[24325]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb5409bec8) and /Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/106.0.5249.103/Libraries/libGLESv2.dylib (0x11f41b668). One of the two will be used. Which one is undefined.
[1013/191402.361483:INFO:headless_shell.cc(660)] Written to file /var/folders/gh/cb238x210j78stqk8llz8_q40000gn/T/tmptd0sxgi5/temp.png.
objc[24335]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb5409bec8) and /Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/106.0.5249.103/Libraries/libGLESv2.dylib (0x11c315668). One of the two will be used. Which one is undefined.
[1013/191403.836538:INFO:headless_shell.cc(660)] Written to file /var/folders/gh/cb238x210j78stqk8llz8_q40000gn/T/tmpap94t4wn/temp.png.
objc[24345]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb5409bec8) and /Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/106.0.5249.103/Libraries/libGLESv2.dylib (0x113cda668). One of the two will be used. Which one is undefined.
[1013/191405.509435:INFO:headless_shell.cc(660)] Written to file /var/folders/gh/cb238x210j78stqk8llz8_q40000gn/T/tmpqg17ubh0/temp.png.

In [ ]:
## 전세도 만들기